name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
          generate-job-summary: false

      - name: Build
        run: ./gradlew build

      - name: Lint
        run: ./gradlew lint

      - name: Check and report lint results
        uses: hidakatsuya/action-report-android-lint@v1.2.0
        with:
          result-path: 'app/build/reports/lint-results-debug.xml'
