name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean assemble

      - name: Lint
        run: ./gradlew lint

      - name: Check and report lint results
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const script = require('.github/workflows/report-lint.js')
            const resultFile = 'app/build/reports/lint-results-debug.txt'
            await script({ core, resultFile })
